apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plexishow.fullname" . }}
  labels:
    {{- include "plexishow.labels" . | nindent 4 }}
data:
  config.yaml: |
{{- toYaml .Values.config | nindent 4 }}
