replicaCount: 1

image:
  repository: ghcr.io/aymerici/plexishow
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: plexishow.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

config:
  m3u_url: ""
  epg_url: ""
  listen_addr: ":8080"
  max_streams: 4
  stream_timeout: "30s"
  refresh_interval: "1h"
  ffmpeg_path: "ffmpeg"
  default_headers:
    token: ""
    referer: ""
    user_agent: ""
