name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_GW_ENDPOINT }}
  OTEL_EXPORTER_OTLP_HEADERS: "Authorization=Bearer ${{ secrets.OTEL_GW_TOKEN }}"
  OTEL_SERVICE_NAME: "plexishow"
  OTEL_RESOURCE_ATTRIBUTES: "service.name=plexishow,ci.branch=${{ github.ref_name }},ci.run=${{ github.run_id }}"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@v2
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
