name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Install Mage
        run: go install github.com/magefile/mage@latest
      - name: Run Release
        run: mage release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
